2025-05-07 15:46:00,687 INFO: Flask API startup [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:49]
2025-05-07 15:46:01,615 INFO: Flask API startup [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:49]
2025-05-07 15:46:06,603 INFO: Request: GET / from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:46:06,603 WARNING: Not found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:101]
2025-05-07 15:46:06,604 INFO: Response status: 404 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:46:06,605 INFO: Response headers: Content-Type: application/json
Content-Length: 179
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:46:06,605 INFO: Response data: {
  "error": "Not found",
  "message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:46:06,650 INFO: Request: GET /favicon.ico from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:46:06,650 WARNING: Not found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:101]
2025-05-07 15:46:06,651 INFO: Response status: 404 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:46:06,651 INFO: Response headers: Content-Type: application/json
Content-Length: 179
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:46:06,652 INFO: Response data: {
  "error": "Not found",
  "message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:46:26,013 INFO: Request: GET /api/test/ from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:46:26,015 WARNING: Not found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:101]
2025-05-07 15:46:26,015 INFO: Response status: 404 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:46:26,015 INFO: Response headers: Content-Type: application/json
Content-Length: 179
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:46:26,016 INFO: Response data: {
  "error": "Not found",
  "message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:46:30,719 INFO: Request: GET /api/test/ from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:46:30,719 WARNING: Not found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:101]
2025-05-07 15:46:30,719 INFO: Response status: 404 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:46:30,719 INFO: Response headers: Content-Type: application/json
Content-Length: 179
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:46:30,720 INFO: Response data: {
  "error": "Not found",
  "message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:46:39,805 INFO: Request: GET /api/test from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:46:39,806 INFO: Response status: 200 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:46:39,806 INFO: Response headers: Content-Type: application/json
Content-Length: 112

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:46:39,806 INFO: Response data: {
  "message": "API is working correctly",
  "status": "success",
  "timestamp": "2025-05-07T15:46:39.806330"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:47:28,557 INFO: Request: POST /api/categories from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:47:28,585 INFO: Category created: bottles [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:281]
2025-05-07 15:47:28,587 INFO: Response status: 201 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:47:28,588 INFO: Response headers: Content-Type: application/json
Content-Length: 191

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:47:28,588 INFO: Response data: {
  "created_at": "Wed, 07 May 2025 15:47:28 GMT",
  "description": "This category was created via Postman",
  "id": 7,
  "name": "bottles",
  "updated_at": "Wed, 07 May 2025 15:47:28 GMT"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 15:48:15,525 INFO: Request: POST /api/categories from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 15:48:15,526 INFO: Response status: 400 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 15:48:15,527 INFO: Response headers: Content-Type: application/json
Content-Length: 56

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 15:48:15,527 INFO: Response data: {
  "error": "Category with this name already exists"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 16:24:04,470 INFO: Request: POST /api/categories from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 16:24:04,473 INFO: Response status: 400 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 16:24:04,474 INFO: Response headers: Content-Type: application/json
Content-Length: 56

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 16:24:04,474 INFO: Response data: {
  "error": "Category with this name already exists"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 16:24:45,480 INFO: Request: POST /api/users/register from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 16:24:45,485 INFO: Response status: 400 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 16:24:45,486 INFO: Response headers: Content-Type: application/json
Content-Length: 41

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 16:24:45,486 INFO: Response data: {
  "error": "Username already exists"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 16:25:47,675 INFO: Request: GET /api/products from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 16:25:47,676 WARNING: Bad request: 400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0) [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:96]
2025-05-07 16:25:47,677 INFO: Response status: 400 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 16:25:47,678 INFO: Response headers: Content-Type: application/json
Content-Length: 134
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 16:25:47,678 INFO: Response data: {
  "error": "Bad request",
  "message": "400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 16:25:52,419 INFO: Request: GET /api/dashboard-data from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 16:25:52,419 WARNING: Bad request: 400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0) [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:96]
2025-05-07 16:25:52,421 INFO: Response status: 400 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 16:25:52,421 INFO: Response headers: Content-Type: application/json
Content-Length: 134
Access-Control-Allow-Origin: *

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
2025-05-07 16:25:52,421 INFO: Response data: {
  "error": "Bad request",
  "message": "400 Bad Request: Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)"
}
 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:81]
2025-05-07 16:28:35,534 INFO: Flask API startup [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:49]
2025-05-07 16:29:53,278 INFO: Request: POST /api/auth/token from 127.0.0.1 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:70]
2025-05-07 16:29:53,527 INFO: Response status: 200 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:78]
2025-05-07 16:29:53,527 INFO: Response headers: Content-Type: application/json
Content-Length: 395

 [in C:\Users\Heer\OneDrive\Desktop\Invento_flask\flask_api\app.py:79]
